<div id = "form-SignUp">

    <div class = "form-column">

        <p>Login:</p>
        <p>Old password:</p>
        <p>New password:</p>
        <p>Retype password:</p>
        <p>Name:</p>
        <p>Surname:</p>
        <p>Email:</p>
        <p>Birthday:</p>
        <p>Avatar:</p>
        </br>
    </div>

    <div class = "form-column">
        <div class = "error-form"><?php echo $data['error']; ?></div>
        <form method="post" action="http://photocommunity/SignUp/submit" enctype="multipart/form-data">
            <input type = "text" name = "login" value = "<?php echo $data['account'][1]; ?>">
            <input type = "password" name = "old_password">
            <input type = "password" name = "password">
            <input type = "password" name = "retype-password">
            <input type = "text" name = "name" value = "<?php echo $data['account'][3]; ?>">
            <input type = "text" name = "surname" value = "<?php echo $data['account'][4]; ?>">
            <input type = "email" name = "email" value = "<?php echo $data['account'][8]; ?>">
            <input type = "date" name = "date" value = "<?php echo $data['account'][6]; ?>">
            <input type = "file" name = "file" value = "<?php echo $data; ?>">
            <input type = "submit" name = "edit" value = "Edit">
        </form>
    </div>

</div>
