<div id = "form-SignUp">

    <div class = "form-column">
        <p>Login:</p>
        <p>Password:</p>
        <p>submit</p>
    </div>

    <div class = "form-column">
        <div class = "error-form"><?php echo $data; ?></div>
        <form method="post" action="http://photocommunity/SignIn/login" enctype="multipart/form-data">
            <input type = "text" name = "login" >
            <input type = "password" name = "password" >
            <input type = "submit" name = "submit" >
        </form>
    </div>

</div>

