<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/Public/Teamplates/style.css">
    <title>PhotoCommunity</title>
</head>
<body>

<div id = "menu">
    <ul>
        <a href="http://photocommunity/Home"><li>Home</li></a>
        <a href="http://photocommunity/SignIn"><li>SignIn</li></a>
        <a href="http://photocommunity/User"><li>Account</li></a>
        <a href="http://photocommunity/SignUp"><li>SignUp</li></a>
        <a href="http://photocommunity/Admin"><li>Admin</li></a>
    </ul>
</div>

<div id ="content">
<?php  require_once($content); ?>
</div>
</body>
</html>